version: '3.8'
services:
  app:
    image: devops-app:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  app-dev:
    profiles: ["dev"]
    image: python:3.11-slim
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && gunicorn -w 1 -b 0.0.0.0:5000 src.app:app"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
