sonar.projectKey=TANIAHR02_devops-gitflow-demo
sonar.organization=taniahr02

sonar.projectName=devops-gitflow-demo

sonar.sources=.
sonar.exclusions=tests/**,.github/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8